### ISSUE TITLE
support 'required' input attribute

### ISSUE THREAD

**Issue by appagg** [PredixDev/px-typeahead#7]
Looking at the code, it doesn't seem like that px-typeahead supports passing a 'required' attribute into the internal input element. Can you add it?

**Comment by runn-vermel** [comment]
@appagg I'm not sure i understand - what would be required?

**Comment by randyaskin** [comment]
Form validation is generally handled by the application, not the component itself. Your app should check whether the `input-value` property is empty, indicating that nothing has been chosen. You could also listen to the `px-typeahead-item-selected` event to figure out if/when a user selects something.

**Comment by randyaskin** [comment]
Changed my mind about adding this. :) Included in v2.2.0. New `required` property will result in validation-error if user blurs past the field without selecting something. Also changed the component so that if the user starts backspacing or clearing the field, the value gets cleared - I figured this made more sense than the previous behavior of retaining last selection.
